language: node_js
matrix:
  include:
    - node_js: '12'
    - node_js: '14'
    - node_js: 'lts/*'
    - node_js: 'node'
      env: NODE_MAIN=true
cache:
  - npm
script:
  - npm run build
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
